version: '3'

services:
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py

  server:
    build: dotnet-docker/samples/aspnetapp
    ports:
      - 5000:80
