version: '3'

services:
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./load_tests:/mnt/locust
    # command: -f /mnt/locust/locustfiles/create_1_job_per_second.py
    command: -f /mnt/locust/locustfiles/create_job_and_wait_until_completed.py

  server:
    build: server2
    ports:
      - 5000:80
