version: '3'

services:
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./load_tests:/mnt/locust/load_tests
    environment:
      - "LOCUST_FILE=${LOCUST_FILE}"
    command: -f /mnt/locust/$LOCUST_FILE

  server:
    build: server2
    ports:
      - 5000:80
